import React, { useState } from 'react';
import { usePharmacyStore } from '../store/usePharmacyStore';

export default function AlertLogsTab() {
    const { notifications, clearLogs } = usePharmacyStore();
    const [logFilter, setLogFilter] = useState('all');

    // Filter notifications
    const filteredNotifications = notifications.filter(n => {
        if (logFilter === 'critical') return n.severity === 'critical';
        if (logFilter === 'warning') return n.severity === 'warning' || n.severity === 'orange';
        return true; // 'all'
    });

    return (
        <section id="tab-notifications-log" className="tab-pane active">
            <div className="page-header flex-header">
                <div>
                    <h2>Notification Alert Logs</h2>
                    <p className="subtitle">Complete history of expiry alerts generated by the system.</p>
                </div>
                <button 
                    className="btn btn-outline" 
                    id="clear-all-logs-btn"
                    onClick={clearLogs}
                >
                    <i className="fa-solid fa-trash-can"></i> Clear All Logs
                </button>
            </div>

            {/* Alert logs wrapper */}
            <div className="card-panel">
                <div className="log-filters">
                    <button 
                        className={`log-filter-btn ${logFilter === 'all' ? 'active' : ''}`}
                        onClick={() => setLogFilter('all')}
                    >
                        All Logs
                    </button>
                    <button 
                        className={`log-filter-btn ${logFilter === 'critical' ? 'active' : ''}`}
                        onClick={() => setLogFilter('critical')}
                    >
                        Critical (Expiry Day/Expired)
                    </button>
                    <button 
                        className={`log-filter-btn ${logFilter === 'warning' ? 'active' : ''}`}
                        onClick={() => setLogFilter('warning')}
                    >
                        Warning (20 / 7 Days)
                    </button>
                </div>
                
                <div className="logs-container" id="logs-container">
                    {filteredNotifications.length === 0 ? (
                        <div className="empty-state">
                            <i className="fa-solid fa-clipboard-check"></i>
                            <p>No logs found matching filter "{logFilter}".</p>
                        </div>
                    ) : (
                        filteredNotifications.map(n => {
                            let iconClass = "fa-bell";
                            if (n.severity === "critical") iconClass = "fa-radiation text-danger";
                            else if (n.severity === "orange") iconClass = "fa-triangle-exclamation text-orange";
                            else if (n.severity === "warning") iconClass = "fa-circle-exclamation text-warning";

                            return (
                                <div key={n.id} className={`log-card ${n.severity}`}>
                                    <div className="log-left">
                                        <i className={`fa-solid ${iconClass}`}></i>
                                        <div className="log-info">
                                            <div className="log-text"><strong>{n.medicineName} (Batch: {n.batch})</strong></div>
                                            <div className="log-text">{n.message}</div>
                                            <div className="log-text" style={{ fontStyle: 'italic', opacity: 0.85, marginTop: '2px' }}>{n.hindiMessage}</div>
                                        </div>
                                    </div>
                                    <div className="log-time">{n.timestamp}</div>
                                </div>
                            );
                        })
                    )}
                </div>
            </div>
        </section>
    );
}
