import React, { useState, useEffect, useCallback } from 'react';
import { usePharmacyStore } from '../store/usePharmacyStore';
import { notificationApi } from '../api/apiClient';

const PAGE_SIZE = 10;

export default function AlertLogsTab() {
    const { clearLogs, notifications: storeNotifications } = usePharmacyStore();

    const [logFilter, setLogFilter]   = useState('all');
    const [currentPage, setCurrentPage] = useState(1);

    // Server-fetched page data
    const [pageData, setPageData]     = useState({ notifications: [], total: 0, totalPages: 1 });
    const [isLoading, setIsLoading]   = useState(false);

    // ── Fetch from server ──────────────────────────────────────────────────────
    const fetchPage = useCallback(async (page, filter) => {
        setIsLoading(true);
        try {
            const params = { page, limit: PAGE_SIZE };

            if (filter === 'critical') params.severity = 'critical';
            else if (filter === 'warning') params.severity = 'warning';

            const { data } = await notificationApi.getAll(params);
            setPageData({
                notifications: data.notifications || [],
                total:         data.total         || 0,
                totalPages:    data.totalPages    || 1,
            });
        } catch {
            setPageData({ notifications: [], total: 0, totalPages: 1 });
        } finally {
            setIsLoading(false);
        }
    }, []);

    // Re-fetch on filter / page / external changes (store updates)
    useEffect(() => {
        fetchPage(currentPage, logFilter);
    }, [currentPage, logFilter, storeNotifications, fetchPage]);

    const handleFilterChange = (filter) => {
        setLogFilter(filter);
        setCurrentPage(1);
    };

    const handleClearLogs = async () => {
        await clearLogs();
        setPageData({ notifications: [], total: 0, totalPages: 1 });
        setCurrentPage(1);
    };

    const safePage   = Math.min(currentPage, pageData.totalPages);
    const totalPages = pageData.totalPages;
    const startItem  = pageData.total === 0 ? 0 : (safePage - 1) * PAGE_SIZE + 1;
    const endItem    = Math.min(safePage * PAGE_SIZE, pageData.total);

    return (
        <section id="tab-notifications-log" className="tab-pane active">
            <div className="page-header flex-header">
                <div>
                    <h2>Notification Alert Logs</h2>
                    <p className="subtitle">Complete history of expiry alerts generated by the system.</p>
                </div>
                <button
                    className="btn btn-outline"
                    id="clear-all-logs-btn"
                    onClick={handleClearLogs}
                >
                    <i className="fa-solid fa-trash-can"></i> Clear All Logs
                </button>
            </div>

            {/* Alert logs wrapper */}
            <div className="card-panel">
                <div className="log-filters">
                    {[
                        { key: 'all',      label: 'All Logs' },
                        { key: 'critical', label: 'Critical (Expiry Day/Expired)' },
                        { key: 'warning',  label: 'Warning (20 / 7 Days)' },
                    ].map(({ key, label }) => (
                        <button
                            key={key}
                            className={`log-filter-btn ${logFilter === key ? 'active' : ''}`}
                            onClick={() => handleFilterChange(key)}
                        >
                            {label}
                        </button>
                    ))}
                </div>

                <div className="logs-container" id="logs-container">
                    {isLoading ? (
                        Array.from({ length: 5 }).map((_, i) => (
                            <div key={i} className="log-card" style={{ animation: 'pulse 1.5s infinite', opacity: 0.5, minHeight: 64 }} />
                        ))
                    ) : pageData.notifications.length === 0 ? (
                        <div className="empty-state">
                            <i className="fa-solid fa-clipboard-check"></i>
                            <p>No logs found matching filter "{logFilter}".</p>
                        </div>
                    ) : (
                        pageData.notifications.map(n => {
                            let iconClass = 'fa-bell';
                            if (n.severity === 'critical') iconClass = 'fa-radiation text-danger';
                            else if (n.severity === 'orange') iconClass = 'fa-triangle-exclamation text-orange';
                            else if (n.severity === 'warning') iconClass = 'fa-circle-exclamation text-warning';

                            return (
                                <div key={n.id || n._id} className={`log-card ${n.severity}`}>
                                    <div className="log-left">
                                        <i className={`fa-solid ${iconClass}`}></i>
                                        <div className="log-info">
                                            <div className="log-text"><strong>{n.medicineName} (Batch: {n.batch})</strong></div>
                                            <div className="log-text">{n.message}</div>
                                            <div className="log-text" style={{ fontStyle: 'italic', opacity: 0.85, marginTop: '2px' }}>{n.hindiMessage}</div>
                                        </div>
                                    </div>
                                    <div className="log-time">{n.timestamp}</div>
                                </div>
                            );
                        })
                    )}
                </div>

                {/* Pagination Controls */}
                {pageData.total > PAGE_SIZE && (
                    <div className="pagination-bar">
                        <span className="pagination-info">
                            {pageData.total === 0
                                ? 'No items'
                                : `Showing ${startItem}–${endItem} of ${pageData.total} logs`
                            }
                        </span>
                        <div className="pagination-controls">
                            <button className="pagination-btn" onClick={() => setCurrentPage(1)} disabled={safePage === 1} title="First Page">
                                <i className="fa-solid fa-angles-left"></i>
                            </button>
                            <button className="pagination-btn" onClick={() => setCurrentPage(p => Math.max(1, p - 1))} disabled={safePage === 1} title="Previous">
                                <i className="fa-solid fa-chevron-left"></i>
                            </button>

                            {Array.from({ length: totalPages }, (_, i) => i + 1)
                                .filter(p => p === 1 || p === totalPages || Math.abs(p - safePage) <= 1)
                                .reduce((acc, p, idx, arr) => {
                                    if (idx > 0 && p - arr[idx - 1] > 1) acc.push('ellipsis-' + idx);
                                    acc.push(p);
                                    return acc;
                                }, [])
                                .map(item =>
                                    typeof item === 'string' ? (
                                        <span key={item} className="pagination-ellipsis">…</span>
                                    ) : (
                                        <button
                                            key={item}
                                            className={`pagination-btn ${safePage === item ? 'active' : ''}`}
                                            onClick={() => setCurrentPage(item)}
                                        >
                                            {item}
                                        </button>
                                    )
                                )
                            }

                            <button className="pagination-btn" onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))} disabled={safePage === totalPages} title="Next">
                                <i className="fa-solid fa-chevron-right"></i>
                            </button>
                            <button className="pagination-btn" onClick={() => setCurrentPage(totalPages)} disabled={safePage === totalPages} title="Last Page">
                                <i className="fa-solid fa-angles-right"></i>
                            </button>
                        </div>
                    </div>
                )}
            </div>
        </section>
    );
}
